package server

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
)

var (
	// ErrClickHousePhysicalSchemaDrift means a release-owned ClickHouse table is
	// missing or its complete physical definition differs from the schema
	// produced by this release's embedded migrations.
	ErrClickHousePhysicalSchemaDrift = errors.New(
		"server: ClickHouse physical schema differs from embedded migrations",
	)
)

const (
	// system.tables.create_table_query is ClickHouse's canonical serialization
	// of the complete table definition. On the version-pinned release server it
	// covers columns, types, defaults, codecs, indexes, constraints, engine,
	// partition/sort/primary keys, TTL, and table settings. Keeping the expected
	// definition release-owned makes a complete migration ledger insufficient
	// to conceal physical schema damage or out-of-band ALTERs.
	clickHousePhysicalSchemaQuery = `
		SELECT
			count(),
			countIf(name = 'schema_migrations'),
			anyIf(create_table_query, name = 'schema_migrations'),
			countIf(name = 'events'),
			anyIf(create_table_query, name = 'events')
		FROM system.tables
		WHERE database = 'open_splunk'`
	clickHouseMigrationLedgerPhysicalSchemaDefinition = "CREATE TABLE open_splunk.schema_migrations (" +
		"`version` UInt32, " +
		"`name` LowCardinality(String), " +
		"`applied_at` DateTime64(3, 'UTC') CODEC(Delta(8), ZSTD(1))" +
		") ENGINE = MergeTree ORDER BY version " +
		"SETTINGS index_granularity = 8192"
	clickHouseEventsPhysicalSchemaDefinition = "CREATE TABLE open_splunk.events (" +
		"`event_id` String CODEC(ZSTD(1)), " +
		"`tenant_id` LowCardinality(String) CODEC(ZSTD(1)), " +
		"`index_name` LowCardinality(String) CODEC(ZSTD(1)), " +
		"`event_time` DateTime64(9, 'UTC') CODEC(Delta(8), ZSTD(1)), " +
		"`index_time` DateTime64(3, 'UTC') CODEC(Delta(8), ZSTD(1)), " +
		"`collected_at` Nullable(DateTime64(9, 'UTC')) CODEC(ZSTD(1)), " +
		"`event_time_source` UInt8 CODEC(T64, ZSTD(1)), " +
		"`host` String CODEC(ZSTD(1)), " +
		"`source` String CODEC(ZSTD(1)), " +
		"`sourcetype` LowCardinality(String) CODEC(ZSTD(1)), " +
		"`service` LowCardinality(Nullable(String)) CODEC(ZSTD(1)), " +
		"`severity` UInt8 CODEC(T64, ZSTD(1)), " +
		"`level` LowCardinality(Nullable(String)) CODEC(ZSTD(1)), " +
		"`body` Nullable(String) CODEC(ZSTD(1)), " +
		"`raw` String CODEC(ZSTD(1)), " +
		"`raw_encoding` UInt8 CODEC(T64, ZSTD(1)), " +
		"`trace_id` Nullable(String) CODEC(ZSTD(1)), " +
		"`span_id` Nullable(String) CODEC(ZSTD(1)), " +
		"`fields` JSON(max_dynamic_types = 16, max_dynamic_paths = 256), " +
		"`field_names` Array(String) CODEC(ZSTD(1)), " +
		"`field_types` Array(UInt8) DEFAULT [] CODEC(ZSTD(1)), " +
		"`field_metadata_version` UInt8 DEFAULT 0 CODEC(T64, ZSTD(1)), " +
		"`collector_id` String CODEC(ZSTD(1)), " +
		"`batch_id` String CODEC(ZSTD(1)), " +
		"`batch_sequence` UInt64 CODEC(Delta(8), ZSTD(1)), " +
		"`visibility_seq` UInt64 DEFAULT 0 CODEC(Delta(8), ZSTD(1)), " +
		"`expires_at` DateTime64(3, 'UTC') CODEC(Delta(8), ZSTD(1)), " +
		"INDEX idx_event_id event_id TYPE bloom_filter(0.001) GRANULARITY 1, " +
		"INDEX idx_trace_id ifNull(trace_id, '') TYPE bloom_filter(0.001) GRANULARITY 1, " +
		"INDEX idx_span_id ifNull(span_id, '') TYPE bloom_filter(0.001) GRANULARITY 1, " +
		"INDEX idx_field_names field_names TYPE text(tokenizer = 'array') GRANULARITY 100000000, " +
		"INDEX idx_raw_text lowerUTF8(raw) TYPE text(tokenizer = 'splitByNonAlpha') GRANULARITY 100000000, " +
		"INDEX idx_visibility_seq visibility_seq TYPE minmax GRANULARITY 1, " +
		"CONSTRAINT visibility_seq_is_positive CHECK visibility_seq > 0, " +
		"CONSTRAINT field_metadata_version_is_supported CHECK field_metadata_version IN (0, 1), " +
		"CONSTRAINT field_metadata_is_aligned CHECK " +
		"((field_metadata_version = 0) AND empty(field_types)) OR " +
		"((field_metadata_version = 1) AND " +
		"(length(field_names) = length(field_types)) AND " +
		"arrayAll(code -> ((code >= 1) AND (code <= 12)), field_types)))" +
		" ENGINE = MergeTree PARTITION BY toYYYYMM(event_time) " +
		"PRIMARY KEY (tenant_id, index_name, toStartOfHour(event_time), event_time) " +
		"ORDER BY (tenant_id, index_name, toStartOfHour(event_time), event_time, event_id) " +
		"TTL expires_at SETTINGS index_granularity = 8192, " +
		"non_replicated_deduplication_window = 10000, " +
		"write_marks_for_substreams_in_compact_parts = 1"
)

// ValidateClickHousePhysicalSchema verifies the exact definitions of both
// tables generated by this release's embedded migrations. It deliberately
// reads only system.tables so the one-shot migrator does not need broader
// metadata grants.
func ValidateClickHousePhysicalSchema(
	ctx context.Context,
	connection ClickHouseVersionConnection,
) error {
	if ctx == nil || connection == nil {
		return errors.New(
			"validate ClickHouse physical schema: context and connection are required",
		)
	}
	if err := ctx.Err(); err != nil {
		return fmt.Errorf("validate ClickHouse physical schema: %w", err)
	}

	var tableCount uint64
	var migrationLedgerCount uint64
	var migrationLedgerDefinition string
	var eventsCount uint64
	var eventsDefinition string
	if err := connection.QueryRow(
		ctx,
		clickHousePhysicalSchemaQuery,
	).Scan(
		&tableCount,
		&migrationLedgerCount,
		&migrationLedgerDefinition,
		&eventsCount,
		&eventsDefinition,
	); err != nil {
		return fmt.Errorf("read ClickHouse physical schema: %w", err)
	}
	if tableCount != 2 || migrationLedgerCount != 1 || eventsCount != 1 {
		return fmt.Errorf(
			"%w: open_splunk table set has total=%d schema_migrations=%d events=%d, want total=2 schema_migrations=1 events=1",
			ErrClickHousePhysicalSchemaDrift,
			tableCount,
			migrationLedgerCount,
			eventsCount,
		)
	}
	if err := validateClickHousePhysicalTableDefinition(
		"schema_migrations",
		migrationLedgerDefinition,
		clickHouseMigrationLedgerPhysicalSchemaDefinition,
	); err != nil {
		return err
	}
	return validateClickHousePhysicalTableDefinition(
		"events",
		eventsDefinition,
		clickHouseEventsPhysicalSchemaDefinition,
	)
}

func validateClickHousePhysicalTableDefinition(
	tableName string,
	actual string,
	expected string,
) error {
	if actual == expected {
		return nil
	}

	digest := fmt.Sprintf("%x", sha256.Sum256([]byte(actual)))
	wantDigest := fmt.Sprintf("%x", sha256.Sum256([]byte(expected)))
	return fmt.Errorf(
		"%w: open_splunk.%s definition SHA-256 is %s, want %s",
		ErrClickHousePhysicalSchemaDrift,
		tableName,
		digest,
		wantDigest,
	)
}
