#!/bin/sh

set -eu
LC_ALL=C
export LC_ALL

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
env_file=${1:-"$script_dir/.env"}

if [ "$#" -gt 1 ]; then
    echo "usage: $0 [output-file]" >&2
    exit 2
fi

env_directory=$(CDPATH= cd -- "$(dirname -- "$env_file")" && pwd)
env_file="$env_directory/$(basename -- "$env_file")"
tls_directory="${env_file}.tls"

case "$env_file" in
    *[!A-Za-z0-9_./\ -]*)
        echo "output path contains shell-unsafe characters: $env_file" >&2
        exit 1
        ;;
esac

if [ -e "$env_file" ]; then
    echo "refusing to overwrite existing $env_file" >&2
    exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is required to generate credentials and the TLS identity" >&2
    exit 1
fi

umask 077
tmp_file=
remove_final_tls=0
cleanup() {
    if [ -n "$tmp_file" ]; then
        rm -f -- "$tmp_file"
    fi
    if [ "$remove_final_tls" -eq 1 ]; then
        rm -rf -- "$tls_directory"
    fi
}
trap cleanup EXIT HUP INT TERM

if ! mkdir -m 0700 -- "$tls_directory"; then
    echo "refusing to overwrite existing $tls_directory" >&2
    exit 1
fi
remove_final_tls=1
tmp_file=$(mktemp "${env_file}.tmp.XXXXXX")

cat >"$tls_directory/ca.conf" <<'EOF'
[req]
distinguished_name = distinguished_name
x509_extensions = v3_ca
prompt = no

[distinguished_name]
CN = Open Splunk local ClickHouse CA

[v3_ca]
basicConstraints = critical, CA:true, pathlen:0
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
EOF

cat >"$tls_directory/server.conf" <<'EOF'
[req]
distinguished_name = distinguished_name
req_extensions = v3_request
prompt = no

[distinguished_name]
CN = clickhouse

[v3_request]
basicConstraints = critical, CA:false
keyUsage = critical, digitalSignature
extendedKeyUsage = serverAuth
subjectAltName = @subject_alt_names
subjectKeyIdentifier = hash

[v3_server]
basicConstraints = critical, CA:false
keyUsage = critical, digitalSignature
extendedKeyUsage = serverAuth
subjectAltName = @subject_alt_names
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer

[subject_alt_names]
DNS.1 = clickhouse
DNS.2 = localhost
IP.1 = 127.0.0.1
IP.2 = ::1
EOF

openssl genpkey \
    -algorithm EC \
    -pkeyopt ec_paramgen_curve:P-256 \
    -out "$tls_directory/ca.key"
openssl req \
    -new \
    -x509 \
    -sha256 \
    -days 3650 \
    -key "$tls_directory/ca.key" \
    -config "$tls_directory/ca.conf" \
    -out "$tls_directory/ca.crt"
openssl genpkey \
    -algorithm EC \
    -pkeyopt ec_paramgen_curve:P-256 \
    -out "$tls_directory/server.key"
openssl req \
    -new \
    -sha256 \
    -key "$tls_directory/server.key" \
    -config "$tls_directory/server.conf" \
    -out "$tls_directory/server.csr"
openssl x509 \
    -req \
    -sha256 \
    -days 825 \
    -in "$tls_directory/server.csr" \
    -CA "$tls_directory/ca.crt" \
    -CAkey "$tls_directory/ca.key" \
    -CAcreateserial \
    -extfile "$tls_directory/server.conf" \
    -extensions v3_server \
    -out "$tls_directory/server.crt"

rm -f -- \
    "$tls_directory/ca.conf" \
    "$tls_directory/ca.key" \
    "$tls_directory/ca.srl" \
    "$tls_directory/server.conf" \
    "$tls_directory/server.csr"
chmod 0644 \
    "$tls_directory/ca.crt" \
    "$tls_directory/server.crt" \
    "$tls_directory/server.key"

bootstrap_password=$(openssl rand -hex 32)
migration_password=$(openssl rand -hex 32)
runtime_password=$(openssl rand -hex 32)
deletion_password=$(openssl rand -hex 32)
{
    echo "# Generated by deploy/generate-env.sh; do not commit this file."
    echo "OPEN_SPLUNK_CLICKHOUSE_BOOTSTRAP_PASSWORD=$bootstrap_password"
    echo "OPEN_SPLUNK_CLICKHOUSE_MIGRATION_PASSWORD=$migration_password"
    echo "OPEN_SPLUNK_CLICKHOUSE_RUNTIME_PASSWORD=$runtime_password"
    echo "OPEN_SPLUNK_CLICKHOUSE_DELETION_PASSWORD=$deletion_password"
    echo "OPEN_SPLUNK_CLICKHOUSE_TLS_CA_FILE=\"$tls_directory/ca.crt\""
    echo "OPEN_SPLUNK_CLICKHOUSE_TLS_CERT_FILE=\"$tls_directory/server.crt\""
    echo "OPEN_SPLUNK_CLICKHOUSE_TLS_KEY_FILE=\"$tls_directory/server.key\""
    echo "OPEN_SPLUNK_CLICKHOUSE_TLS_SERVER_NAME=clickhouse"
} >"$tmp_file"

# The adjacent hard link is an atomic no-overwrite publication. Once the
# complete TLS directory is retained, interruption can leave either no env
# file or an env file that always references a complete identity.
remove_final_tls=0
if ! ln -- "$tmp_file" "$env_file"; then
    remove_final_tls=1
    echo "refusing to overwrite existing $env_file" >&2
    exit 1
fi
rm -f -- "$tmp_file"
tmp_file=
trap - EXIT HUP INT TERM

echo "wrote $env_file and $tls_directory with permissions restricted by umask 077"
