#!/bin/sh

set -eu
LC_ALL=C
export LC_ALL

if [ "${1:-}" != "--development" ] || [ "$#" -gt 2 ]; then
    echo "usage: $0 --development [output-file]" >&2
    exit 2
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
output_file=${2:-"$script_dir/.env.development"}
case "$output_file" in
    /*) ;;
    *) output_file="$PWD/$output_file" ;;
esac

if [ -e "$output_file" ]; then
    echo "refusing to overwrite existing $output_file" >&2
    exit 1
fi
if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is required to generate development credentials" >&2
    exit 1
fi

output_directory=$(dirname -- "$output_file")
mkdir -p "$output_directory"
chmod 0700 "$output_directory"

clickhouse_password=$(openssl rand -hex 32)
administrator_token=$(openssl rand -base64 48 | tr -d '\n')
temporary_file="$output_file.tmp.$$"
trap 'rm -f -- "$temporary_file"' EXIT HUP INT TERM

umask 077
{
    echo "# Generated by deploy/generate-env.sh; do not commit this file."
    echo "OPEN_SPLUNK_SERVER_CLICKHOUSE_ADDRESS=127.0.0.1:${OPEN_SPLUNK_DEPLOY_CLICKHOUSE_NATIVE_PORT:-9000}"
    echo "OPEN_SPLUNK_DEPLOY_CLICKHOUSE_NATIVE_PORT=${OPEN_SPLUNK_DEPLOY_CLICKHOUSE_NATIVE_PORT:-9000}"
    echo "OPEN_SPLUNK_SERVER_CLICKHOUSE_USERNAME=clickhouse"
    echo "OPEN_SPLUNK_SERVER_CLICKHOUSE_PASSWORD=$clickhouse_password"
    echo "OPEN_SPLUNK_SERVER_ADMINISTRATOR_TOKEN=$administrator_token"
    echo "OPEN_SPLUNK_DEPLOY_HTTP_PORT=${OPEN_SPLUNK_DEPLOY_HTTP_PORT:-8080}"
} >"$temporary_file"
chmod 0600 "$temporary_file"
mv -- "$temporary_file" "$output_file"
trap - EXIT HUP INT TERM
