#!/bin/sh

set -eu
LC_ALL=C
export LC_ALL

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "usage: $0 --production|--development [output-file]" >&2
    exit 2
fi
case "$1" in
    --production) default_name=.env ;;
    --development) default_name=.env.development ;;
    *)
        echo "usage: $0 --production|--development [output-file]" >&2
        exit 2
        ;;
esac

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
output_file=${2:-"$script_dir/$default_name"}
case "$output_file" in
    /*) ;;
    *) output_file="$PWD/$output_file" ;;
esac
case "$output_file" in
    */)
        echo "output must name a file, not a directory" >&2
        exit 2
        ;;
esac

if [ -e "$output_file" ] || [ -L "$output_file" ]; then
    echo "refusing to overwrite existing $output_file" >&2
    exit 1
fi
if [ "$1" = "--development" ] && ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is required to generate development credentials" >&2
    exit 1
fi

umask 077
output_directory=$(dirname -- "$output_file")
mkdir -p "$output_directory"
if [ "$1" = "--development" ]; then
    chmod 0700 "$output_directory"
fi
temporary_directory=$(mktemp -d "$output_directory/.open-splunk-env.XXXXXXXX")
temporary_file="$temporary_directory/$(basename -- "$output_file")"
trap 'rm -f -- "$temporary_file"; rmdir -- "$temporary_directory"' EXIT
trap 'exit 1' HUP INT TERM

if [ "$1" = "--production" ]; then
    cat "$script_dir/.env.example" >"$temporary_file"
else
    clickhouse_password=$(openssl rand -hex 32)
    administrator_token=$(openssl rand -base64 48 | tr -d '\n')
    {
        echo "# Generated by deploy/generate-env.sh; do not commit this file."
        echo "OPEN_SPLUNK_SERVER_CLICKHOUSE_ADDRESS=127.0.0.1:${OPEN_SPLUNK_DEPLOY_CLICKHOUSE_NATIVE_PORT:-9000}"
        echo "OPEN_SPLUNK_DEPLOY_CLICKHOUSE_NATIVE_PORT=${OPEN_SPLUNK_DEPLOY_CLICKHOUSE_NATIVE_PORT:-9000}"
        echo "OPEN_SPLUNK_SERVER_CLICKHOUSE_USERNAME=clickhouse"
        echo "OPEN_SPLUNK_SERVER_CLICKHOUSE_PASSWORD=$clickhouse_password"
        echo "OPEN_SPLUNK_SERVER_ADMINISTRATOR_TOKEN=$administrator_token"
        echo "OPEN_SPLUNK_DEPLOY_HTTP_PORT=${OPEN_SPLUNK_DEPLOY_HTTP_PORT:-8080}"
    } >"$temporary_file"
fi
chmod 0600 "$temporary_file"
# The directory form keeps the basename and fails if any destination entry
# already exists, including a symlink or a concurrent invocation's file.
ln "$temporary_file" "$output_directory/"
