export const OPEN_SPLUNK_APPLICATION_VERSION =
  process.env.NEXT_PUBLIC_OPEN_SPLUNK_APPLICATION_VERSION ?? "0.1.0";
export const OPEN_SPLUNK_SOURCE_REVISION =
  process.env.NEXT_PUBLIC_OPEN_SPLUNK_SOURCE_REVISION ?? "development";

export const OPEN_SPLUNK_BUILD_LABEL = OPEN_SPLUNK_SOURCE_REVISION === "development"
  ? `v${OPEN_SPLUNK_APPLICATION_VERSION} · development`
  : `v${OPEN_SPLUNK_APPLICATION_VERSION} · rev ${OPEN_SPLUNK_SOURCE_REVISION.slice(0, 12)}`;
