package clickhouse

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/Suhaibinator/open-splunk/internal/plan"
	"github.com/Suhaibinator/open-splunk/internal/spl"
	"github.com/Suhaibinator/open-splunk/internal/testsupport/officialspl"
)

const (
	officialGoldenCorpusPath = "../spl/testdata/official_compatibility.json"
	officialGoldenDirectory  = "testdata/golden"
	// officialGoldenUpdateEnv rewrites every golden file from the current
	// compiler output. It is refused under CI so a stale snapshot can never be
	// silently regenerated by the pipeline that is supposed to catch it.
	officialGoldenUpdateEnv = "OPEN_SPLUNK_UPDATE_GOLDEN"
)

// TestOfficialCorpusGoldenSQL compiles every source-backed official SPL case
// and compares the complete executable contract (SQL, bind arguments, public
// schema, transport descriptors, and execution seal digest) with
// testdata/golden/<case-id>.sql. Any lowering change therefore surfaces as a
// reviewable diff instead of a silent behavior change, and a case that starts
// or stops compiling is a diff too because errors are snapshotted as well.
//
// Regenerate with OPEN_SPLUNK_UPDATE_GOLDEN=1 and review the git diff.
func TestOfficialCorpusGoldenSQL(t *testing.T) {
	t.Parallel()

	update := officialGoldenUpdateRequested(t)
	corpus := loadOfficialGoldenCorpus(t)
	for _, testCase := range corpus.Cases {
		t.Run(testCase.ID, func(t *testing.T) {
			t.Parallel()
			got := renderOfficialGolden(t, testCase)
			path := filepath.Join(officialGoldenDirectory, testCase.ID+".sql")
			if update {
				if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
					t.Fatalf("write golden %s: %v", path, err)
				}
				t.Logf("updated golden %s", path)
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read golden %s (set %s=1 to create it): %v", path, officialGoldenUpdateEnv, err)
			}
			if strings.TrimSpace(string(want)) != strings.TrimSpace(got) {
				t.Fatalf("compiled contract differs from %s (set %s=1 to regenerate)\ngot:\n%s\n\nwant:\n%s",
					path, officialGoldenUpdateEnv, got, want)
			}
		})
	}
}

// TestOfficialGoldenFilesMatchCorpus keeps the golden directory and the
// official corpus in exact correspondence: every case has a snapshot and no
// snapshot outlives its case.
func TestOfficialGoldenFilesMatchCorpus(t *testing.T) {
	t.Parallel()

	update := officialGoldenUpdateRequested(t)
	corpus := loadOfficialGoldenCorpus(t)
	caseIDs := make([]string, 0, len(corpus.Cases))
	for _, testCase := range corpus.Cases {
		caseIDs = append(caseIDs, testCase.ID)
	}
	slices.Sort(caseIDs)

	entries, err := os.ReadDir(officialGoldenDirectory)
	if err != nil {
		t.Fatalf("read golden directory: %v", err)
	}
	fileIDs := make([]string, 0, len(entries))
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".sql") {
			t.Fatalf("unexpected entry %q in %s: only <case-id>.sql files belong here", name, officialGoldenDirectory)
		}
		id := strings.TrimSuffix(name, ".sql")
		if _, found := slices.BinarySearch(caseIDs, id); !found {
			if update {
				if err := os.Remove(filepath.Join(officialGoldenDirectory, name)); err != nil {
					t.Fatalf("remove stale golden %s: %v", name, err)
				}
				t.Logf("removed stale golden %s", name)
				continue
			}
			t.Errorf("golden %s has no official corpus case (set %s=1 to remove it)", name, officialGoldenUpdateEnv)
			continue
		}
		fileIDs = append(fileIDs, id)
	}
	for _, id := range caseIDs {
		if _, found := slices.BinarySearch(fileIDs, id); !found && !update {
			t.Errorf("official case %q has no golden file (set %s=1 to create it)", id, officialGoldenUpdateEnv)
		}
	}
}

func officialGoldenUpdateRequested(t *testing.T) bool {
	t.Helper()
	if os.Getenv(officialGoldenUpdateEnv) != "1" {
		return false
	}
	if os.Getenv("CI") != "" {
		t.Fatalf("%s=1 is refused under CI; regenerate golden files locally and commit them", officialGoldenUpdateEnv)
	}
	return true
}

func loadOfficialGoldenCorpus(t *testing.T) officialspl.Corpus {
	t.Helper()
	corpus, err := officialspl.Load(officialGoldenCorpusPath)
	if err != nil {
		t.Fatalf("load official SPL corpus: %v", err)
	}
	return corpus
}

// officialGoldenScope is the fixed execution boundary shared by every golden
// case. The corpus queries all address index=main, and the authorized set is
// deliberately wider than the requested set so the compiled read scope proves
// that authored SPL narrows within trusted authority rather than defining it.
func officialGoldenScope(testCase officialspl.Case) plan.Scope {
	scope := testChartScope()
	scope.RequestedIndexes = []string{"main"}
	scope.AuthorizedIndexes = []string{"main", "gradethis"}
	if testCase.ID == "addinfo.no-arguments" {
		// addinfo requires an admitted search-job identifier; the golden
		// harness is a non-executing validation caller.
		scope.AllowUnboundSearchJobID = true
	}
	return scope
}

func renderOfficialGolden(t *testing.T, testCase officialspl.Case) string {
	t.Helper()
	var builder strings.Builder
	fmt.Fprintf(&builder, "-- official SPL case: %s\n", testCase.ID)
	fmt.Fprintf(&builder, "-- source: %s (%s)\n", testCase.Source.URL, testCase.Source.Section)
	fmt.Fprintf(&builder, "-- query: %s\n", testCase.Query)

	compiled, err := compileOfficialGoldenCase(t, testCase)
	if err != nil {
		if diagnostic, ok := errors.AsType[*spl.Diagnostic](err); ok {
			fmt.Fprintf(&builder, "-- error: %s: %s\n", diagnostic.Code, diagnostic.Message)
		} else {
			fmt.Fprintf(&builder, "-- error: %v\n", err)
		}
		return builder.String()
	}

	fmt.Fprintf(&builder, "-- output_fields: %s\n", strings.Join(compiled.OutputFields, ", "))
	if len(compiled.OutputPresentations) != 0 {
		fmt.Fprintf(&builder, "-- output_presentations: %#v\n", compiled.OutputPresentations)
	}
	if len(compiled.ContainerOutputs) != 0 {
		fmt.Fprintf(&builder, "-- container_outputs: %#v\n", compiled.ContainerOutputs)
	}
	if len(compiled.OptionalMultivalueOutputs) != 0 {
		fmt.Fprintf(&builder, "-- optional_multivalue_outputs: %#v\n", compiled.OptionalMultivalueOutputs)
	}
	if len(compiled.StringOrBytesOutputs) != 0 {
		fmt.Fprintf(&builder, "-- string_or_bytes_outputs: %#v\n", compiled.StringOrBytesOutputs)
	}
	fmt.Fprintf(&builder, "-- sparse_fields: %t subset=%t\n", compiled.SparseFields, compiled.SparseFieldsSubset)
	if compiled.Timechart != nil {
		fmt.Fprintf(&builder, "-- timechart: %#v\n", *compiled.Timechart)
	}
	if compiled.Chart != nil {
		fmt.Fprintf(&builder, "-- chart: %#v\n", *compiled.Chart)
	}
	fmt.Fprintf(&builder, "-- atomic_result: %t\n", compiled.RequiresAtomicResult())
	if hint, ok := compiled.StatsPartitionsMaxThreadsHint(); ok {
		fmt.Fprintf(&builder, "-- stats_partitions_max_threads: %d\n", hint)
	}
	digest, sealed := compiled.ExecutionAuthorityDigest()
	if !sealed {
		t.Fatalf("compiled %s has no valid execution seal", testCase.ID)
	}
	fmt.Fprintf(&builder, "-- execution_authority_digest: %s\n", hex.EncodeToString(digest[:]))
	for index, argument := range compiled.Args {
		fmt.Fprintf(&builder, "-- args[%d]: %#v\n", index, argument)
	}
	if got, want := strings.Count(compiled.SQL, "?"), len(compiled.Args); got != want {
		t.Fatalf("placeholder count = %d, args = %d", got, want)
	}
	builder.WriteString(compiled.SQL)
	builder.WriteString("\n")
	return builder.String()
}

func compileOfficialGoldenCase(t *testing.T, testCase officialspl.Case) (CompiledQuery, error) {
	t.Helper()
	parsed, err := spl.Parse(testCase.Query)
	if err != nil {
		return CompiledQuery{}, err
	}
	logical, err := plan.Build(parsed, officialGoldenScope(testCase))
	if err != nil {
		return CompiledQuery{}, err
	}
	resolutions := officialGoldenLookupResolutions(t, logical)
	if len(resolutions) == 0 {
		return (Compiler{}).Compile(logical)
	}
	return (Compiler{}).CompileWithLookupResolutions(logical, resolutions)
}

// officialGoldenLookupResolutions pins one deterministic asset version for
// every lookup stage so the snapshot covers the sealed external-table
// transport. Column names come from the corpus query's own key and output
// spellings; the payload is fixed so the digest is reproducible.
func officialGoldenLookupResolutions(t *testing.T, logical *plan.Query) []LookupResolution {
	t.Helper()
	var resolutions []LookupResolution
	for _, operator := range logical.Operators {
		lookup, ok := operator.(*plan.Lookup)
		if !ok {
			continue
		}
		headerSet := make(map[string]struct{})
		for _, key := range lookup.Keys {
			headerSet[key.LookupField] = struct{}{}
		}
		for _, output := range lookup.Outputs {
			headerSet[output.LookupField] = struct{}{}
		}
		headers := make([]string, 0, len(headerSet))
		for header := range headerSet {
			headers = append(headers, header)
		}
		sort.Strings(headers)
		rows := make([][]string, 0, 2)
		for rowIndex := range 2 {
			row := make([]string, len(headers))
			for columnIndex, header := range headers {
				row[columnIndex] = fmt.Sprintf("%s-%d", header, rowIndex+1)
			}
			rows = append(rows, row)
		}
		payload := strings.Join(headers, ",") + "\n"
		for _, row := range rows {
			payload += strings.Join(row, ",") + "\n"
		}
		resolution, err := NewLookupResolution(
			"tenant-1",
			lookup.DefinitionName,
			"asset-"+lookup.DefinitionName,
			1,
			uint64(len(payload)),
			sha256.Sum256([]byte(payload)),
			headers,
			rows,
		)
		if err != nil {
			t.Fatalf("NewLookupResolution(%s): %v", lookup.DefinitionName, err)
		}
		bound, err := resolution.WithLogicalContract(*lookup, "lookup-"+lookup.DefinitionName, 1)
		if err != nil {
			t.Fatalf("WithLogicalContract(%s): %v", lookup.DefinitionName, err)
		}
		resolutions = append(resolutions, bound)
	}
	return resolutions
}
